In [48]:
# Import Libraries

import pandas as pd

# Pedestrian Volume Data

In [49]:
# Read in the pedestrian volume data

ped_volume = pd.read_csv('../data/Pedestrian_Counting_System_-_Monthly__counts_per_hour_.csv')

In [50]:
ped_volume.tail()

,ID,Date_Time,Year,Month,Mdate,Day,Time,Sensor_ID,Sensor_Name,Hourly_Counts
3860326,3860327,08/31/2021 11:00:00 PM,2021,August,31,Tuesday,23,72,Flinders St-ACMI,2
3860327,3860328,08/31/2021 11:00:00 PM,2021,August,31,Tuesday,23,75,Spring St- Flinders St (West),1
3860328,3860329,08/31/2021 11:00:00 PM,2021,August,31,Tuesday,23,76,Macaulay Rd-Bellair St,1
3860329,3860330,08/31/2021 11:00:00 PM,2021,August,31,Tuesday,23,77,Harbour Esplanade (West) - Ped Path,4
3860330,3860331,08/31/2021 11:00:00 PM,2021,August,31,Tuesday,23,78,Harbour Esplanade (West) - Bike Path,0

In [51]:
ped_volume.dtypes

ID                int64
Date_Time        object
Year              int64
Month            object
Mdate             int64
Day              object
Time              int64
Sensor_ID         int64
Sensor_Name      object
Hourly_Counts     int64
dtype: object

In [52]:
ped_volume = ped_volume.drop("ID", axis=1)

In [53]:
# No empty cell presents

ped_volume.isna().any(axis=None)

False

In [54]:
# Extract the time
pattern = r'([0-9]*/)*(20[0-9]*) '

In [55]:
ped_volume["Time"] = ped_volume["Date_Time"].str.replace(pattern, '', regex=True)
ped_volume = ped_volume.drop("Date_Time", axis=1)

In [56]:
ped_volume

,Year,Month,Mdate,Day,Time,Sensor_ID,Sensor_Name,Hourly_Counts
0,2019,November,1,Friday,05:00:00 PM,34,Flinders St-Spark La,300
1,2019,November,1,Friday,05:00:00 PM,39,Alfred Place,604
2,2019,November,1,Friday,05:00:00 PM,37,Lygon St (East),216
3,2019,November,1,Friday,05:00:00 PM,40,Lonsdale St-Spring St (West),627
4,2019,November,1,Friday,05:00:00 PM,36,Queen St (West),774
...,...,...,...,...,...,...,...,...
3860326,2021,August,31,Tuesday,11:00:00 PM,72,Flinders St-ACMI,2
3860327,2021,August,31,Tuesday,11:00:00 PM,75,Spring St- Flinders St (West),1
3860328,2021,August,31,Tuesday,11:00:00 PM,76,Macaulay Rd-Bellair St,1
3860329,2021,August,31,Tuesday,11:00:00 PM,77,Harbour Esplanade (West) - Ped Path,4
3860330,2021,August,31,Tuesday,11:00:00 PM,78,Harbour Esplanade (West) - Bike Path,0

# Sensor Location Data

In [65]:
# Read in the pedestrian sensor location data

sensor_loc = pd.read_csv('../data/Pedestrian_Counting_System_-_Sensor_Locations.csv')
sensor_loc

,sensor_id,sensor_description,sensor_name,installation_date,status,note,direction_1,direction_2,latitude,longitude,location
0,55,Elizabeth St-La Trobe St (East),Eli380_T,2018/07/19,A,NaN,North,South,-37.809889,144.961343,"(-37.80988941, 144.96134331)"
1,45,Little Collins St-Swanston St (East),Swa148_T,2017/06/29,A,NaN,North,South,-37.814141,144.966094,"(-37.81414074, 144.9660938)"
2,61,RMIT Building 14,RMIT14_T,2019/06/28,A,NaN,North,South,-37.807675,144.963091,"(-37.80767455, 144.96309115)"
3,7,Birrarung Marr,Fed_T,2014/12/17,A,NaN,East,West,-37.818629,144.971694,"(-37.81862929, 144.97169395)"
4,72,Flinders St- ACMI,ACMI_T,2020/11/30,A,NaN,East,West,-37.817263,144.968728,"(-37.81726337, 144.96872809)"
...,...,...,...,...,...,...,...,...,...,...,...
72,21,Bourke St-Russell St (West),Rus180_T,2013/09/02,A,NaN,South,North,-37.812447,144.967788,"(-37.81244703, 144.96778757)"
73,78,Harbour Esplanade (West) - Bike Path,HarEsB_T,2021/03/30,A,NaN,North,South,-37.814716,144.944651,"(-37.81471642, 144.9446508)"
74,77,Harbour Esplanade (West) - Pedestrian path,HarEsP_T,2021/03/25,A,NaN,North,South,-37.814414,144.944330,"(-37.81441438, 144.94433026)"
75,35,Southbank,SouthB_T,2021/04/15,A,River side,East,West,-37.820178,144.965089,"(-37.82017828, 144.96508877)"
76,6,Flinders Street Station Underpass,FliS_T,2009/03/25,A,Upgraded on 8/09/21,North,South,-37.819117,144.965583,"(-37.81911704, 144.96558256)"

### Inactive or Removed Sensors

In [66]:
sensor_loc[sensor_loc["status"] != "A"]

,sensor_id,sensor_description,sensor_name,installation_date,status,note,direction_1,direction_2,latitude,longitude,location
10,60,Flinders La - Swanston St (West) Temporary,Swa31T_T,2019/03/08,R,Temporary for the duration of the metro tunnel...,North,South,-37.816682,144.966895,"(-37.81668188, 144.9668954)"
16,15,State Library,QV_T,2009/03/25,R,NaN,South,North,-37.810644,144.964471,"(-37.81064378, 144.96447132)"
25,33,Flinders St-Spring St (West),Spr13_T,2014/04/23,R,NaN,North,South,-37.814833,144.974541,"(-37.81483252, 144.97454056)"
26,13,Flagstaff Station,Wil277_T,2009/03/24,R,NaN,NaN,NaN,-37.812397,144.956527,"(-37.81239679, 144.95652653)"
31,38,Flinders St-Swanston St (West),Swa11_T,2014/12/05,R,Device has been removed (17/02/2017),NaN,NaN,-37.817234,144.967150,"(-37.81723437, 144.96715033)"
32,32,City Square,CSq_T,2013/12/20,R,Device has been removed (24/01/2017),NaN,NaN,-37.815737,144.966857,"(-37.81573742, 144.96685718)"
57,16,Australia on Collins,Col270_T,2009/03/30,R,Device moved to location ID 53 (22/09/2015),NaN,NaN,-37.815734,144.965210,"(-37.81573423, 144.96521044)"

In [67]:
sensor_loc = sensor_loc.drop(["sensor_name", "location", "note", "sensor_description"], axis=1)

Four of them has empty directions. These instances won't be dropped for now as they have substantial pedestrian count in the other dataframe.

In [73]:
# Join the two dataframe
complete_df = ped_volume.merge(sensor_loc, left_on='Sensor_ID', right_on='sensor_id')

In [75]:
complete_df.to_pickle("../data/Pedestrian_Count_Location.pkl")